version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3500:3500"
    environment:
      - NODE_ENV=production
      - PORT=3500
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3500/healthz', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3500/api/tasks
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: task-app-network 