apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      imagePullSecrets:
      - name: gcr-registry-secret
      containers:
      - name: frontend
        image: us-central1-docker.pkg.dev/jenkins-proj2/frontend-repo/frontend:3
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://aaqibhussain.link/api/tasks"
        ports:
        - containerPort: 3000